version: "3"

services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/certs.d:/etc/nginx/certs.d
        command: nginx -g 'daemon off;'
