version: "3"

services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 443:443
        volumes:
            - ./nginx/certs.d:/etc/nginx/certs.d
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled

networks:
    default:
        external: true
        name: web
